# Generated by Django 4.0.7 on 2023-12-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_remove_transaction_seller_transaction_credit_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer_new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
