# Generated by Django 4.0.7 on 2023-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
