# Generated by Django 4.0.7 on 2023-12-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_baseuser_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='verify_type',
            field=models.IntegerField(blank=True, choices=[(1, 'PHONENUMBER'), (2, 'PASSWORD')], null=True),
        ),
    ]
