# Generated by Django 4.0.7 on 2023-12-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_verify_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
